@endpoint=http://localhost:{{$dotenv PORT}}/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsImlhdCI6MTcxNjgyNTc4NCwiZXhwIjoxNzE2ODQzNzg0fQ.XUfscWyMvS3W9EL3n8d5jMD6n1BqMkmX5jPJoIKlgoE
### Erreur 404
GET {{endpoint}}/truc

### Documentation
GET {{endpoint}}/api/doc

### Inscription
POST {{endpoint}}/signup
Content-Type: application/json

{
    "email": "test@test.fr",
    "lastname": "Test",
    "firstname": "Test",
    "pseudo": "Test",
    "password": "Test2024!",
    "role_id": 1
}

### Inscription en erreur mot de passe
POST {{endpoint}}/signup
Content-Type: application/json

{
    "email": "test2@test2.fr",
    "lastname": "Test2",
    "firstname": "Test2",
    "pseudo": "Test2",
    "password": "Test",
    "role_id": 1
}

### Connexion
POST {{endpoint}}/login
Content-Type: application/json

{
    "email": "test@test.fr",
    "password": "Test2024!"
}

### Récupération de son carnet de voyage
GET {{endpoint}}/me/trips
Authorization: Bearer {{token}}

### Récupération du voyage avec l'id 1
GET {{endpoint}}/me/trips/1
Authorization: Bearer {{token}}

### Récupération d'un voyage qui n'existe pas
GET {{endpoint}}/me/trips/199

### Création d'un voyage en erreur a cause d'un oubli
POST {{endpoint}}/me/trips
Content-Type: application/json

{
   "title": "Nouveau voyage"
}

# ### Création d'un voyage en erreur a cause d'un souci de caractère
# POST {{endpoint}}/trips
# Content-Type: application/json

# {
#     "date_start": "2021-01-01",
#     "date_end": "2021-01-31",
#     "photo": "photo.jpg",
#     "title": "Norvège ",
#     "description": "Description du voyage",
#     "note": 4,
#     "user_id": 1
# }

### Création d'un voyage
# @name tripInsert
POST {{endpoint}}/me/trips
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "dateStart": "2021-01-01",
    "dateEnd": "2021-01-31",
    "photo": "photo.jpg",
    "title": "Nouveau voyage",
    "description": "Description du voyage",
    "note": 4,
    "user_id": 11
}

### Modification du voyage avec l'id voyageInsert
PATCH {{endpoint}}/me/trips/{{tripInsert.response.body.data.id}}

Content-Type: application/json
Authorization: Bearer {{token}}
{  "trip_id": 12,
    "date_start": "2021-01-01",
    "date_end": "2021-01-31",
    "title": "Nouveau voyage bis",
    "description": "Description du voyage",
    "note": 4
   }

### Suppression du voyage avec l'id voyageInsert
DELETE {{endpoint}}/me/trips/{{tripInsert.response.body.data.id}}
Authorization: Bearer {{token}}